from src.pipeline.data_ingestion_pipeline import DataIngestionPipeline
from src.pipeline.data_validation_pipeline import DataValidationPipeline
from src.pipeline.data_transformation_pipeline import DataTransformationPipeline



#data Ingestion Pipeline
data_ingestion_pipeline_obj=DataIngestionPipeline()
data_ingestion_artifacts=data_ingestion_pipeline_obj.initiate_data_ingestion_pipeline()
print(data_ingestion_artifacts)


#data Validation Pipeline
data_validation_pipeline_obj=DataValidationPipeline()
data_validation_artifacts=data_validation_pipeline_obj.initiate_data_validation_pipeline()
print(data_validation_artifacts)



#data Transformation Pipeline


data_transformation_pipeline_obj=DataTransformationPipeline()
data_transformation_artifacsts=data_transformation_pipeline_obj.initiate_data_transformation_pipeline()
