name: CI to AWS ECR

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the 'main' branch.

jobs:
  build-and-push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the Code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. Set up AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 4. Build and Tag the Docker Image
    - name: Build Docker Image
      run: |
        docker build -t my-app:latest .
        docker tag my-app:latest ${{ secrets.AWS_ECR_REPOSITORY_URI }}

    # 5. Push Docker Image to Amazon ECR
    - name: Push Docker Image to ECR
      run: |
        docker push ${{ secrets.AWS_ECR_REPOSITORY_URI }}